### PR TITLE
[OFFAPPS-1037] Clean up old scaffolding in master branch

### PR DESCRIPTION
**Pull request by yu-tian113**
[OFFAPPS-1037] Replace master branch with offapps-migration branch. Create new readme documentation and ADR

## Description
This PR is part of ticket [OFFAPPS-1037](https://zendesk.atlassian.net/browse/OFFAPPS-1037), cleaning up the old scaffold.

## Tasks
- [x] Branch off master, cleaning up old scaffold

## References
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1037)

@zendesk/apps-migration
@zendesk/vegemite 

## Risks

### CODE REVIEW

**Comment by keitheous** [comment]
👍

**Comment by yu-tian113** [comment]
@hoangtrvu ah, I'll create a new one in the new scaffold branch which will be merged into this branch.
the old one would fail with all the deletions here 😆

**Comment by vaevictis** [comment]
I guess it's because we don't use Travis on any of the Official Apps!

**Comment by yu-tian113** [comment]
.travis.yml is added in [tony/new-scaffold](https://github.com/zendesk/app_scaffold/tree/tony/new-scaffold) branch.
CI check will pass after that branch is merged to this one.

**Pull request merged**
