### PR TITLE
[FROM-SRATCH] switch to Zendesk-produced app-bootstrap instead of the we…

### PR DESCRIPTION
**Pull request by sandlerr**
…ll-known `bootstrap` library and add some usage examples to the templates

cc @zendesk/vegemite

### CODE REVIEW

**Comment by danielbreves** [comment]
@chucknado @pmgrove @jzempel we'll need to discuss how we can make http://zendeskgarden.github.io public. Any plans to update https://garden.zendesk.com?

**Comment by jzempel** [comment]
There is a desire (and some pressure) to update garden.zendesk.com. But without the resources, we have no feasible concrete plan for doing so.

**Comment by nick-f** [comment]
@sandlerr Seeing as how we are now using Garden in the from-scratch branch, can we close this?

**Comment by sandlerr** [comment]
Yep!

**Pull request closed without merging**
